# Generated by Django 4.0.5 on 2022-07-12 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(blank=True, default=0)),
                ('repeat_count', models.CharField(blank=True, default='0', max_length=255)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('public', 'PUBLIC'), ('private', 'PRIVATE')], default='public', max_length=10)),
                ('titel', models.CharField(max_length=255)),
                ('item', models.ManyToManyField(related_name='programs_item', to='app_sports_program.item')),
                ('user', models.ManyToManyField(blank=True, related_name='programs_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
